import os
from github import Github
from dotenv import load_dotenv
import time
load_dotenv()


def open_pull_request(repo_full_name: str, file_relative_path: str, fixed_code: str,
                       branch_name: str = None, base_branch: str = "main") -> str:
    if branch_name is None:
        branch_name = f"patchpilot-fix-{int(time.time())}"
    """
    Repo'da yangi branch ochadi, tuzatilgan faylni commit qiladi va Pull Request yaratadi.
    repo_full_name: masalan "abdumuxtorabdullajonov9-cmyk/patchpilot"
    Qaytaradi: yaratilgan PR havolasi.
    """
    token = os.environ["GITHUB_TOKEN"]
    gh = Github(token)
    repo = gh.get_repo(repo_full_name)

    base = repo.get_branch(base_branch)
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base.commit.sha)
    except Exception:
        pass  # Branch allaqachon mavjud bo'lsa, davom etamiz

    contents = repo.get_contents(file_relative_path, ref=branch_name)
    repo.update_file(
        path=file_relative_path,
        message=f"PatchPilot: fix security vulnerabilities in {file_relative_path}",
        content=fixed_code,
        sha=contents.sha,
        branch=branch_name,
    )

    pr = repo.create_pull(
        title=f"PatchPilot: automated security fix for {file_relative_path}",
        body="This PR was automatically generated by PatchPilot.\n\n"
             "It fixes security vulnerabilities detected by Semgrep and verified "
             "by re-scanning after the fix was applied.",
        head=branch_name,
        base=base_branch,
    )

    return pr.html_url